name: Serial Scanner

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
        default: NARKOZ/hacker-scripts
        description: 'owner/repo format for example NARKOZ/hacker-scripts for https://github.com/NARKOZ/hacker-scripts'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install required dependencies and run script
        run: |
          python3 -m pip install --upgrade pip
          pip install "requests[security]"  # Installs requests with compatible urllib3
          pip install urllib3==1.26.15       # Specify a compatible version
          pip install chardet==4.0.0         # Specify a compatible version
          pip install semgrep
          pip install -r requirements.txt
          pip install "tablib[xlsx]"
          go install github.com/go-enry/go-license-detector/v4/cmd/license-detector@latest
          file ~/go/bin/license-detector
          python main.py ${{ secrets.GH_TOKEN }} ${{ inputs.repo }}
        shell: sh

      - name: Uploading the output
        uses: actions/upload-artifact@v4
        with:
          name: output-download
          path: output.xlsx

      - name: Delete repo
        env:
          GH_DL_TOKEN: ${{ secrets.GH_DL_TOKEN }}
        run: |
          OWNER=${{ github.repository_owner }}; REPO=$(echo "${{ inputs.repo }}" | cut -d'/' -f2); echo "$REPO"; curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_DL_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/$OWNER/$REPO"
        shell: sh
        continue-on-error: true
